### ISSUE TITLE
DBT-DuckDB 1.8.3 doesn't appear to work with DuckDB 1.1.0

### ISSUE THREAD

**Issue by williamkaper** [duckdb/dbt-duckdb#442]
We tried upgrading our DuckDB python library to 1.1.0 and started seeing odd errors like the following (which we are seeing when trying to Connect to MotherDuck as well)

```
16:56:30    Runtime Error in test dbt_utils_unique_combination_of_columns_export_contract_item_pts_contract_item_pt_src_id__most_recent_version_number (models/export/schema.yml)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""
16:56:30
16:56:30    Runtime Error in snapshot stg_ss_invoice_items (snapshots/core_data/stg_ss_invoice_items.sql)
  INTERNAL Error: Attempted to access index 1 within vector of size 1
  This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
  For more information, see https://duckdb.org/docs/dev/internal_errors
16:56:30
16:56:30    Runtime Error in model export_invoices (models/export/export_invoices.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"
16:56:30
16:56:30    Runtime Error in model export_cost_of_revenue (models/export/export_cost_of_revenue.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""
16:56:30
16:56:30    Runtime Error in model export_cost_of_revenue_item_returns (models/export/export_cost_of_revenue_item_returns.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""
```

Does DBT-DuckDB need a version of a DuckDB or DBT library bumped to get it working in sync with 1.1.0?

**Comment by Alex-Monahan** [comment]
Hi William! 
Are there any other details that you are able to share about your dataset and your queries? These kinds of errors have historically been DuckDB bugs (but anything is possible of course!), so a reproduction would be a huge help.

**Comment by williamkaper** [comment]
I'm trying to look at each table and see if I can squash whatever is causing the bug. Most of the export tables seems like it was related to a window function that was sorting timestamps in desc order (PG sorts ASC Nulls Last, DESC NULLs First), but it seemed like DuckDB does it opposite so I had to explicitly state DESC NULLS last which seemed to drop those off the list. (it wasn't causing any issue in DuckDB 1.0.0, though it may have been sorting different then as well) 

A second model was reporting a duplicate CTE alias. The CTE (materialized) was referenced in another CTE that wasn't materialized. Once I materialized the second CTE, that table's issue went away. 

I'm still seeing the issue on a few models, and I can't see anything obvious. I'm happy to share debug logs or even set up a working session to share screen so you can see the models we are using and the dataset

**Comment by jwills** [comment]
Hey William, there were a couple of 1.1.0-specific issues I ran into and fixed here: https://github.com/duckdb/dbt-duckdb/pull/440

I haven't cut a new release yet as there was still some stuff we wanted to test out on DuckDB 1.1.0, but if you want to see if the code in master fixes the issues you are seeing, you can do a `pip install git+https://github.com/duckdb/dbt-duckdb.git@master`

**Comment by williamkaper** [comment]
It resolved a few of the issues I had above, but there are still some that it didn't resolve. I'm trying to see if I can narrow down what in the model that's giving the runtime error

**Comment by williamkaper** [comment]
```
00:32:33  Completed with 15 errors and 0 warnings:
00:32:33
00:32:33    Runtime Error in model export_invoice_item_components (models/export/export_invoice_item_components.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""
00:32:33
00:32:33    Runtime Error in snapshot stg_ss_invoice_items (snapshots/core_data/stg_ss_invoice_items.sql)
  INTERNAL Error: Attempted to access index 1 within vector of size 1
  This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
  For more information, see https://duckdb.org/docs/dev/internal_errors
00:32:33
00:32:33    Runtime Error in model export_contract_item_discounts (models/export/export_contract_item_discounts.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""
00:32:33
00:32:33    Runtime Error in model export_invoices (models/export/export_invoices.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""
00:32:33
00:32:33    Runtime Error in model export_payments (models/export/export_payments.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""""
00:32:33
00:32:33    Runtime Error in model export_payment_disputes (models/export/export_payment_disputes.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""""
00:32:33
00:32:33    Runtime Error in model int_contract_item_discounts (models/intermediate/int_contract_item_discounts.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""""""
00:32:33
00:32:33    Runtime Error in model int_contract_item_pts (models/intermediate/int_contract_item_pts.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""""""
00:32:33
00:32:33    Runtime Error in model int_contract_item_refunds (models/intermediate/int_contract_item_refunds.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""""""""
00:32:33
00:32:33    Runtime Error in model int_contract_item_taxes (models/intermediate/int_contract_item_taxes.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""""""""
00:32:33
00:32:33    Runtime Error in model int_cost_of_revenue (models/intermediate/int_cost_of_revenue.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""""""""""
00:32:33
00:32:33    Runtime Error in test dbt_utils_unique_combination_of_columns_export_contract_item_pts_contract_item_pt_src_id__most_recent_version_number (models/export/schema.yml)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1""""""""""""""
00:32:33
00:32:33    Runtime Error in test dbt_utils_unique_combination_of_columns_export_contract_bundled_discounts_contract_bundled_discount_src_id__most_recent_version_number (models/export/schema.yml)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""""""""""""
00:32:33
00:32:33    Runtime Error in model int_core_book_entry_components_balancing_unwind (models/intermediate/int_core_book_entry_components_balancing_unwind.sql)
  FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
  Original error: "Attempted to access index 1 within vector of size 1"""""""""""""
00:32:33
00:32:33    on-run-end failed, error:
 FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "Attempted to access index 1 within vector of size 1""""""""""""""""
00:32:33
00:32:33  Done. PASS=77 WARN=0 ERROR=15 SKIP=107 TOTAL=199
DBT failed! Exiting!
```

I am happy to share what the stg_ss_invoice_items model is doing offline/outside of ticket, but it's essentially a snapshot that is taking a bunch of other tables and doing a grouping query with sums (its in need of a refactor, but it worked fine in DuckDB 1.0.0)

**Comment by williamkaper** [comment]
@jwills @Alex-Monahan I just sent you both a group slack message on the motherduck community page with the source for the actual model that is blowing up.

**Comment by guenp** [comment]
Closing this for now because I think it's been resolved but please reopen if it occurs again!
